<a href="https://colab.research.google.com/github/sunnatillo91/ai-datascience/blob/main/2_1_3_Arr_Or_Pr_4Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum
Ma'lumotlar tahlili.


2.1. NumPy kutubxonasi bilan ishlash
NumPy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.3. Massivga yo'naltirilgan dasturlash

# Tartiblash (Sorting)

In [4]:
# data
arr = np.random.rand(4) # 4 ta taxminiy elementdan tuzilgan massiv
arr

array([0.13765295, 0.51962157, 0.7588475 , 0.10430485])

In [10]:
# sort funksiyasi
# 1-usul
sorted_arr = np.sort(arr)  # arr1 ning tartiblangan ko'rinishini sorted_arr ga joylaydi
sorted_arr

array([0.10430485, 0.13765295, 0.51962157, 0.7588475 ])

In [11]:
# 2-usul
arr.sort()  # arr ning tartiblangan ko'rinishi
arr

array([0.10430485, 0.13765295, 0.51962157, 0.7588475 ])

In [12]:
# teskari tartiblash
rev_arr = -np.sort(-arr)  # teskari tartibdagi arr
rev_arr

array([0.7588475 , 0.51962157, 0.13765295, 0.10430485])

In [16]:
# 2D array (massiv)
arr2d = np.random.randn(3,4)  # (3, 4) random massiv
arr2d


array([[ 0.37561172,  0.77952266,  0.93856282, -0.45219345],
       [ 0.9777856 , -0.25529699,  0.43008935, -1.51180305],
       [ 2.57213283, -0.93489483, -0.75220952,  0.5324528 ]])

In [17]:
# axis = 0  --> Qator
row_srt = np.sort(arr2d, axis=0)  # arr2d ning har bir qator bo'yicha tartiblangan ko'rinishi
row_srt

array([[ 0.37561172, -0.93489483, -0.75220952, -1.51180305],
       [ 0.9777856 , -0.25529699,  0.43008935, -0.45219345],
       [ 2.57213283,  0.77952266,  0.93856282,  0.5324528 ]])

In [19]:
# axis = 0  --> Ustun
col_srt = np.sort(arr2d, axis=1)  # arr2d ning har bir ustun bo'yicha tartiblangan ko'rinishi
col_srt

array([[-0.45219345,  0.37561172,  0.77952266,  0.93856282],
       [-1.51180305, -0.25529699,  0.43008935,  0.9777856 ],
       [-0.93489483, -0.75220952,  0.5324528 ,  2.57213283]])