<a href="https://colab.research.google.com/github/sunnatillo91/ai-datascience/blob/main/2_1_3_Arr_Or_Pr_1_Math%26Stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum
Ma'lumotlar tahlili.


2.1. NumPy kutubxonasi bilan ishlash
NumPy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.3. Massivga yo'naltirilgan dasturlash

#Matematik va statistik amallarni qo'llash

# Ko'paytirish, bo'lish, qo'shish, ayirish va h.k. amallar

In [2]:
# data
arr1 = np.random.randn(5,4) # 5 ga 4 bo'lgan o'lchamli massiv
arr1

array([[-0.78135637,  0.4807153 , -0.79577139, -0.49663732],
       [-1.69752253, -0.89875083, -0.18195254,  0.67409445],
       [ 0.3311076 , -1.16701047, -1.50876886,  1.08496991],
       [-0.65874428,  1.36620033,  0.65598758, -0.92102494],
       [-0.65218522, -1.45557113, -0.62797138,  2.14349729]])

In [3]:
# sum metodi
arr1.sum()  # arr1 ning barcha elementlarini yig'indisini hisoblaydi

-5.106694802454257

In [4]:
np.sum(arr1)  # arr1 ning barcha elementlarini yig'indisini hisoblaydi

-5.106694802454257

In [5]:
arr1.sum(axis=1)  # arr1 ning qator yig'indisi

array([-1.59304978, -2.10413145, -1.25970182,  0.44241868, -0.59223043])

In [6]:
arr1.sum(axis=0)  # arr1 ning ustun yig'indisi

array([-3.4587008 , -1.67441681, -2.45847659,  2.4848994 ])

# mean metodi

In [7]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [8]:
np.mean(data)  # massiv elementlarining o'rtacha qiymatini qaytaradi

2.0

In [9]:
np.mean(arr1)   # arr1 elementlarining o'rtacha qiymatini qaytaradi

-0.25533474012271284

In [10]:
np.mean(arr1, axis=1)   # qator bo'yicha o'rtacha qiymatni qaytaradi

array([-0.39826245, -0.52603286, -0.31492546,  0.11060467, -0.14805761])

In [11]:
arr1.mean(axis=0)  #ustun bo'yicha o'rtacha qiymatni qaytaradi

array([-0.69174016, -0.33488336, -0.49169532,  0.49697988])

# **cumsum** metodi

In [12]:
data

array([0, 1, 2, 3, 4])

In [14]:
data.cumsum()  # o'zidan oldingi elementlar yig'indisiga o'sha elementni qo'shib element o'rniga yozadi

array([ 0,  1,  3,  6, 10])