<a href="https://colab.research.google.com/github/sunnatillo91/ai-datascience/blob/main/2_1_3_Arr_Or_Pr_1_Logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum
Ma'lumotlar tahlili.


2.1. NumPy kutubxonasi bilan ishlash
NumPy kutubxonasini chaqirib olish

In [2]:
import numpy as np

2.1.3. Massivga yo'naltirilgan dasturlash

Mantiqiy shart operatorlarni massiv operator sifatida qo'llash


Shart operatori sifatida where dan foydalanish


Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: xarr va yarr. Agarda shart Trueni qanoatlantirsa xarr elementini qabul qilgan aksincha esa yarr elementini qabul qilgan yangi massiv hosil qilinsin.

In [3]:
# Massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) # xarr
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) # yarr

In [4]:
# Shart
cond = np.array([True, False, True, True, False])

In [5]:
# where
result = np.where(cond, xarr, yarr)  # cond == True : xarr, cond == False : yarr elementi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [7]:
arr = np.random.randn(4,4)  # (4, 4) taxminiy massiv
arr

array([[ 0.01102349,  0.0913337 , -0.8783854 , -0.65499711],
       [ 1.83700106, -1.37430908, -0.67500883, -1.66487465],
       [-0.19340224,  0.92106008,  0.18458187,  0.12052091],
       [ 0.39370008, -0.2793734 ,  0.08005745,  0.24284771]])

In [8]:
# where
results = np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarini esa 2ga almashtiramiz
results

array([[ 2,  2, -2, -2],
       [ 2, -2, -2, -2],
       [-2,  2,  2,  2],
       [ 2, -2,  2,  2]])