<a href="https://colab.research.google.com/github/sunnatillo91/ai-datascience/blob/main/3_Indexing%26Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Indeks va kesib olish asoslari

In [1]:
import numpy as np

In [4]:
arr = np.arange(10,100,10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
arr[2], arr[-2]

(30, 80)

Massivdan kerakli elementlarni kesib olish

In [8]:
arr[4:6]  # 4 dan 6 gacha (6 kirmaydi) bo'lgan elementlarni kesib qaytaradi
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

#Numpy kutubxonasida massivning kesib olingan qismiga o'zgartirish kiritilsa asosiy manba massivga ta'sir qiladi

In [9]:
sliced_arr = arr[3:5]
sliced_arr[:] = 0
sliced_arr

array([0, 0])

In [10]:
arr

array([10, 20, 30,  0,  0, 60, 70, 80, 90])

copy() metodi

In [13]:
arr1 = np.arange(10,100,10)
sliced_arr1 = arr1[4:6].copy()
sliced_arr1[:] = 0  # kesib olingan elementlarni hammasini 0 ga tenglashtiramiz
sliced_arr1

array([0, 0])

In [14]:
arr1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

#2 o'lchamli (2d array) massivlarda indeks va kesib olish

In [15]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr2d[1,1]

5

In [17]:
arr2d[2,2]

9

#2 o'lchamli massivlarning bir nechta elementlarini kesib olish

In [18]:
sl_arr2d = arr2d[2, 1:3]
sl_arr2d

array([8, 9])

In [19]:
sl_arr2d = arr2d[2, 1:]
sl_arr2d

array([8, 9])

#3 o'lchamli massivlarda indeks va kesib olish

In [20]:
# 3D array
arr3d = np.array([[[ 0, 1, 2],
                   [ 3, 4, 5],
                   [ 6, 7, 8]],

                   [[9, 10, 11],
                    [12, 13, 14],
                    [15, 16, 17]],

                   [[18, 19, 20],
                    [21, 22, 23],
                    [24, 25, 26]]])

arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [23]:
arr3d[1][2, 1:3]

array([16, 17])

In [24]:
arr3d[2][1, 1:]

array([22, 23])