<a href="https://colab.research.google.com/github/sunnatillo91/ai-datascience/blob/main/_1_Creating_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum

Ma'lumotlar tahlili

2.1 NumPy kutubxonasi bilan ishlash

# NumPy kutubxonasini chaqirib olish

In [1]:
import numpy as np

# 2.1.1 N-o'lchamli massiv (array)larga ishlov berish

# NumPyda massiv yaratishning eng oson yo'llaridan biri bu array funksiyasi yordamida amalga oshiriladi. Ushbu funksiya har qanday turdagi ketma-ket ma'lumotlarni qabul qilib, uni yangi numpy arrayiga o'girib beradi.

In [3]:
data1 = [3.5, 5, 6, 2]  # list
arr1 = np.array(data1)  # array1

In [7]:
arr1, data1

(array([3.5, 5. , 6. , 2. ]), [3.5, 5, 6, 2])

In [9]:
data2 = (4,5,3.2,7)   # tuple
arr2 = np.array(data2)  # numpy da yaratilgan array

In [10]:
data2, arr2

((4, 5, 3.2, 7), array([4. , 5. , 3.2, 7. ]))

# Massiv o'lchami

In [11]:
arr1.ndim # array1 ning o'lchami

1

# Ikki va undan ortiq o'lchamli massivlar

In [15]:
data3 = [[1,2,3,4,], [5,6,7,8], [10,11,12,13]]  # list ichidagi list (nested list)
arr3 = np.array(data3)  # array3

In [22]:
arr3.ndim  # array3 ning o'lchami

2

In [29]:
data4 = [[[1,2,3,4],[5,6,7,8]]]  # list ichidagi list (nested list)
data5 = [[[1,2,3],[4,5,6]]]  # list ichidagi list (nested list)
arr4 = np.array(data4)   # ikki o'lchamli massivlar
arr5 = np.array(data5)   # uch o'lchamli massivlar

In [30]:
arr5.ndim

3

# shape, size metodlari

**shape** metodi massivning qator va ustunlar sonini, **size** esa massivlardagi elementlar sonini ko'rsatadi

In [35]:
arr3.shape  # array4 ning qator va ustunlar sonini ko'rsatadi (qator, ustun)

(2, 4)

In [36]:
arr3.size  # array3 ning elementlar sonini ko'rsatadi

8

# N-o'lchamli massivlar yaratishning boshqa usullari

**zeros** va **ones** funksiyalari yordamida massivlar yaratish

In [41]:
arr6 = np.zeros(shape =(2,4))  # barcha elementlari 0 ga teng array
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
arr7 = np.ones((2,5))  # barcha elementlari 1 ga teng array
arr7

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

arrange funksiyasi yordamida yaratish

In [46]:
arr8 = np.arange(4, 20, 2)  # 4 dan 20 gacha bo'lgan qiymatlarni 2 qadam bilan massiv yaratdi
arr8

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
arr9 = np.arange(20)  # 0 dan 20 gacha bo'lgan qiymatlarni 1 qadam bilan massiv yaratdi
arr9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])