<a href="https://colab.research.google.com/github/sunnatillo91/ai-datascience/blob/main/_4_Boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Boolean indekslash

In [2]:
import numpy as np


In [3]:
# Ismlar:

names = np.array(['Hasan', 'Husan', 'Salim','Hasan', 'Olim', 'Hasan', 'Muhammad', 'Umar'])
names

array(['Hasan', 'Husan', 'Salim', 'Hasan', 'Olim', 'Hasan', 'Muhammad',
       'Umar'], dtype='<U8')

In [4]:
# data
data = np.random.randn(8, 4)
data

array([[ 2.05627375, -0.16711296,  0.97976138,  0.26260918],
       [ 0.92395825, -1.48872305,  0.36239535, -0.77530265],
       [-1.14777548,  0.39391151,  1.36558396, -0.69375908],
       [-0.54213973,  1.00521258, -0.41566296,  1.20149731],
       [ 0.71642097, -1.32323751, -0.06906236, -0.81480393],
       [ 1.08531908, -1.27601366, -1.80714153, -0.84834374],
       [ 0.76674499,  1.04684557, -1.81881626,  0.68084702],
       [ 0.58721578, -0.3765769 , -1.18718553, -0.33603293]])

In [5]:
names == 'Hasan'

array([ True, False, False,  True, False,  True, False, False])

In [6]:
data[names == 'Hasan']  # Hasanga tegishli barcha ma'lumotlarni ajratib olish

array([[ 2.05627375, -0.16711296,  0.97976138,  0.26260918],
       [-0.54213973,  1.00521258, -0.41566296,  1.20149731],
       [ 1.08531908, -1.27601366, -1.80714153, -0.84834374]])

In [7]:
data[names == 'Olim']

array([[ 0.71642097, -1.32323751, -0.06906236, -0.81480393]])

In [8]:
data[names == 'Salim', 2:]  # Salimga tegishli oxirgi ikki ustundagi ma'lumotlarni ajratib olish


array([[ 1.36558396, -0.69375908]])

In [9]:
data[names == 'Muhammad', 2:4]

array([[-1.81881626,  0.68084702]])

In [10]:
data[names != 'Olim']  # (!=) Olimdan tashqari barcha insonlarning ma'lumotlarini ajratib olish

array([[ 2.05627375, -0.16711296,  0.97976138,  0.26260918],
       [ 0.92395825, -1.48872305,  0.36239535, -0.77530265],
       [-1.14777548,  0.39391151,  1.36558396, -0.69375908],
       [-0.54213973,  1.00521258, -0.41566296,  1.20149731],
       [ 1.08531908, -1.27601366, -1.80714153, -0.84834374],
       [ 0.76674499,  1.04684557, -1.81881626,  0.68084702],
       [ 0.58721578, -0.3765769 , -1.18718553, -0.33603293]])

In [11]:
data[~(names == 'Olim')]  # (~) yuqoridagi cell bilan bir xil vazifani bajaradi

array([[ 2.05627375, -0.16711296,  0.97976138,  0.26260918],
       [ 0.92395825, -1.48872305,  0.36239535, -0.77530265],
       [-1.14777548,  0.39391151,  1.36558396, -0.69375908],
       [-0.54213973,  1.00521258, -0.41566296,  1.20149731],
       [ 1.08531908, -1.27601366, -1.80714153, -0.84834374],
       [ 0.76674499,  1.04684557, -1.81881626,  0.68084702],
       [ 0.58721578, -0.3765769 , -1.18718553, -0.33603293]])

In [18]:
print(names)
print(data)

['Hasan' 'Husan' 'Salim' 'Hasan' 'Olim' 'Hasan' 'Muhammad' 'Umar']
[[ 2.05627375 -0.16711296  0.97976138  0.26260918]
 [ 0.92395825 -1.48872305  0.36239535 -0.77530265]
 [-1.14777548  0.39391151  1.36558396 -0.69375908]
 [-0.54213973  1.00521258 -0.41566296  1.20149731]
 [ 0.71642097 -1.32323751 -0.06906236 -0.81480393]
 [ 1.08531908 -1.27601366 -1.80714153 -0.84834374]
 [ 0.76674499  1.04684557 -1.81881626  0.68084702]
 [ 0.58721578 -0.3765769  -1.18718553 -0.33603293]]


In [19]:
mask = (names == 'Hasan') | (names == 'Husan')  # ikki ismdan biri yoki har ikkalasi
mask

array([ True,  True, False,  True, False,  True, False, False])

In [21]:
data[mask]  # Hasan va Husanlarga tegishli ma'lumotlarni ajratib olish

array([[ 2.05627375, -0.16711296,  0.97976138,  0.26260918],
       [ 0.92395825, -1.48872305,  0.36239535, -0.77530265],
       [-0.54213973,  1.00521258, -0.41566296,  1.20149731],
       [ 1.08531908, -1.27601366, -1.80714153, -0.84834374]])

In [22]:
data[data<0]

array([-0.16711296, -1.48872305, -0.77530265, -1.14777548, -0.69375908,
       -0.54213973, -0.41566296, -1.32323751, -0.06906236, -0.81480393,
       -1.27601366, -1.80714153, -0.84834374, -1.81881626, -0.3765769 ,
       -1.18718553, -0.33603293])

In [24]:
data[data<0] = 0
data

array([[2.05627375, 0.        , 0.97976138, 0.26260918],
       [0.92395825, 0.        , 0.36239535, 0.        ],
       [0.        , 0.39391151, 1.36558396, 0.        ],
       [0.        , 1.00521258, 0.        , 1.20149731],
       [0.71642097, 0.        , 0.        , 0.        ],
       [1.08531908, 0.        , 0.        , 0.        ],
       [0.76674499, 1.04684557, 0.        , 0.68084702],
       [0.58721578, 0.        , 0.        , 0.        ]])