<a href="https://colab.research.google.com/github/sunnatillo91/ai-datascience/blob/main/_Transposing%26Swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Science va Sun'iy Intellekt Praktikum
Ma'lumotlar tahlili.
2.1. NumPy kutubxonasi bilan ishlash
NumPy kutubxonasini chaqirib olish

In [1]:
import numpy as np

2.1.1. N-o'lchamli massiv (array)larga ishlov berish
Massivlar pozitsiyasini ko'chirish Transpose va o'qlar o'rnini almashtirish Swapping axes

reshape metodi

In [5]:
A = np.arange(6).reshape(3,2)  # A massiv : Elementlari 0~6 gacha , shape (3, 2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
A.T   # A massivning Trasnpose ko'rinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

# `swaping axes`

In [7]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
A.swapaxes(1, 0) #A massivining Transpose ko'rinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

# Transpose ning ishlatilishiga misol

In [10]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
np.dot(A, A.T)  # AA^T  bir turdagi massivni ikkinchi turdagi massivga ko'paytirish

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])