<a href="https://colab.research.google.com/github/sunnatillo91/ai-datascience/blob/main/Copy_of_2_1_3_Arr_Or_Pr_2_Arithmetic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum
Ma'lumotlar tahlili.


2.1. NumPy kutubxonasi bilan ishlash
NumPy kutubxonasini chaqirib olish

In [2]:
import numpy as np

2.1.3. Massivga yo'naltirilgan dasturlash

Arifmetik amallar

# Ko'paytirish, bo'lish, qo'shish, ayirish va h.k. amallar

In [3]:
# data
arr1 = np.arange(6).reshape(2,3) # 0 dan 6 gacha bo'lgan elementlardan tashkil topgan array
arr2 = np.arange(6, 12).reshape(2,3) # 6 dan 12 gacha bo'lgan elementlardan tashkil topgan array
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
# Ko'paytirish
arr1 * arr2  # arr1 ning elementlarini arr2 ning mos elementlariga ko'paytiradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [7]:
# bo'lish
arr1 / arr2  # arr1 ning elementlarini arr2 ning mos elementlariga bo'ladi

array([[0.        , 0.14285714, 0.25      ],
       [0.33333333, 0.4       , 0.45454545]])

In [8]:
arr1 + arr2  # arr1 ning elementlarini arr2 ning mos elementlariga qo'shadi

array([[ 6,  8, 10],
       [12, 14, 16]])

In [9]:
# ayirish
arr1 - arr2  # arr1 ning elementlarini arr2 ning mos elementlarini ayirish

array([[-6, -6, -6],
       [-6, -6, -6]])

In [10]:
# kvadratga oshirish (square)
arr1**2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [11]:
# kvadrat ildiz (sqrt)
arr2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])