<a href="https://colab.research.google.com/github/sunnatillo91/ai-datascience/blob/main/mohirdev_NumPy_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
arr1 = np.zeros(shape=(1,9))
np.size(arr1)

9

#### 4. Massiv yarating va uning xotira hajmini toping.



In [ ]:
arr2 = np.zeros(shape=(3,2))
np.size(arr2)

6

`💡Ishora` size, itemsize

In [ ]:
arr2.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vektor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
arr4 = np.zeros(shape=(12,1))
arr4[5] = 1
arr4

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr5 = np.arange(20,60)
arr5

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
arr5 = np.arange(20,60)
rev_arr5 = -np.sort(-arr5)
rev_arr5

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr6 = np.arange(12,21).reshape(3,3)
arr6

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
arr7 = np.array([3, 7, 0, 0, 9, 0])
arr8 = np.nonzero(arr7)
arr8

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
#data = [[1,2], [5,6], [10,11]]  # list ichidagi list (nested list)
arr9 = np.random.randn(2,2,2)
arr9

array([[[ 0.22646232, -1.40494841],
        [ 1.10224227,  0.50667711]],

       [[ 1.2784778 ,  1.14994159],
        [-1.70944916,  0.36411091]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr10 = np.random.randn(9,9)
arr10

array([[ 0.90748324,  0.34366523,  0.31384243,  1.50057824, -0.53331323,
        -0.4877348 , -0.03963976, -1.07725018,  0.87640965],
       [ 0.44462278,  0.7494136 ,  0.37850588, -0.43182717,  0.67857385,
        -0.89531057, -0.94817537, -0.78804875, -0.34085475],
       [ 0.93036192,  1.95104207,  0.18558318, -1.20186332,  0.66891989,
        -0.58494816, -2.10600143,  1.49964101, -0.24557762],
       [ 1.14996812,  0.83103162,  0.59040346,  1.22645433,  0.57147951,
        -1.14952465,  1.21846623, -0.18364038, -1.55502048],
       [-0.93958011,  0.39583999,  0.87740958,  0.51403272, -0.25871239,
        -0.0965286 , -0.87214271, -0.74985742, -0.25796224],
       [-1.59006833,  0.09262989, -0.81932061,  2.02973035, -1.62399099,
         0.18956142, -0.01777033, -0.05275977,  0.71466738],
       [ 1.36238628,  2.17251338,  0.08236255, -0.06968194,  1.18011986,
        -0.6845209 , -0.70241845, -1.02010907, -0.104736  ],
       [-0.2205781 , -2.05081026,  0.02874441,  0.01648789,  1

In [ ]:
arr_min = np.min(arr10)
arr_min

-2.106001434476187

In [ ]:
arr_max = np.max(arr10)
arr_max

2.172513384213349

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
# 0 * np.nan
print(0 * np.nan)

# np.nan == np.nan
print(np.nan == np.nan)

# np.inf > np.nan
print(np.inf > np.nan)

# np.nan - np.nan
print(np.nan - np.nan)

# np.nan in set([np.nan])
print(np.nan in set([np.nan]))

# 0.7 == 7 * 0.1
print(0.7 == 7 * 0.1)

nan
False
False
nan
True
False


#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
a = np.ones((6,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a_b = np.dot(a,b)
a_b

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [1]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a = [1,2]
a

[1, 2]

In [ ]:
b = [4, 5]
b

[4, 5]

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [1]:
import numpy as np
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-1-779629cb3f15>:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-1-779629cb3f15>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-1-779629cb3f15>:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [7]:
a = np.arange(6)
b = np.arange(8)
c = np.intersect1d(a,b)
c

array([0, 1, 2, 3, 4, 5])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

In [18]:
a = np.random.randn(8)
a

array([ 1.27278749,  1.8550028 ,  3.02807579, -0.08213225,  0.83491547,
       -0.70074744,  0.27875465, -0.19740843])

`💡Ishora` %, np.floor, astype, np.trunc

In [19]:
pos_arr = a[a>0]
qoldiq, butun = np.modf(pos_arr)
butun

array([1., 1., 3., 0., 0.])

In [23]:
b = np.floor(pos_arr)
b

array([1., 1., 3., 0., 0.])

In [25]:
c = pos_arr.astype(np.int64)
c

array([1, 1, 3, 0, 0])

In [26]:
d = np.trunc(pos_arr)
d

array([1., 1., 3., 0., 0.])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [44]:
arr = np.array([[i for i in range(3)] for _ in range(3)])
arr

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [48]:
arr = np.random.randn(10)
sorted_arr = np.sort(arr)
sorted_arr

array([-1.32440473, -0.52363223, -0.40121204, -0.38323909, -0.22881866,
       -0.22590209, -0.151929  ,  0.08109067,  1.20804858,  1.41123975])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [58]:
A = np.arange(12)
A
#B = np.arange(6,16)
B = np.arange(12)

In [60]:
C = np.allclose(A,B)
C

True

In [62]:
D = np.array_equal(A,B)
D

True

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [65]:
arr = np.arange(18).reshape(6,3)
arr
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
arr_arr1 = np.dot(arr,arr1)
arr_arr1

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218],
       [164, 203, 242, 281],
       [200, 248, 296, 344]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [75]:
arr2 = np.random.randn(5)
arr2

array([-0.64278692, -0.01754697, -0.45973531, -1.22232422, -1.4864291 ])

In [86]:
max_index = np.argmax(arr2)
max_index

1

In [87]:
arr2[max_index] = 0
arr2

array([-0.64278692,  0.        , -0.45973531, -1.22232422, -1.4864291 ])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [100]:
yesterday = np.datetime64('2024-02-23')
print(f"kechagi sana: {yesterday}")

kechagi sana: 2024-02-23


In [101]:
today = np.datetime64('today')
print(f"Bugungi sana: {today}")

Bugungi sana: 2024-02-24


In [102]:
tomorrow = np.datetime64('2024-02-25')
print(f"Ertangi sana: {tomorrow}")

Ertangi sana: 2024-02-25


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [106]:
dates = np.arange('2016-01-01', '2016-02-01', dtype='datetime64[D]')
dates

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [29]:
a = np.random.randn(8)
a

array([-1.28790414,  0.21980821,  0.34042033,  0.39822494, -1.11890304,
        1.21539783, -0.15172663, -0.80721232])

In [31]:
pos_num = a[a>0]
pos_int = pos_num % 1
pos_int

array([0.21980821, 0.34042033, 0.39822494, 0.21539783])

In [32]:
b = np.floor(pos_num)
b

array([0., 0., 0., 1.])

In [33]:
c = pos_num.astype(np.int64)
c

array([0, 0, 0, 1])

In [35]:
d = np.trunc(pos_num)
d

array([0., 0., 0., 1.])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yig'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [56]:
x = np.random.randn(4)
y = np.random.randn(4)
result = np.sum(x+ y)
result

-1.1650989520743331

In [55]:
%time for _ in range(10): result*2

CPU times: user 10 µs, sys: 2 µs, total: 12 µs
Wall time: 14.3 µs


In [96]:
import numpy as np

array1 = np.random.randint(low = 1, high = 10, size = 5)
array2 = np.random.randint(low = 1, high = 10, size = 5)

loop_sum = 0
for i in range(len(array1)):
    loop_sum += array1[i] + array2[i]

np_sum = np.sum(array1) + np.sum(array2)

print("Sum using loop:", loop_sum)
print("Sum using np.sum:", np_sum)

Sum using loop: 46
Sum using np.sum: 46


In [97]:
%time for _ in range(10): loop_sum*2


CPU times: user 12 µs, sys: 2 µs, total: 14 µs
Wall time: 16.7 µs


In [100]:
%time for _ in range(10): np_sum*2

CPU times: user 13 µs, sys: 1e+03 ns, total: 14 µs
Wall time: 18.4 µs


In [102]:
13/12

1.0833333333333333

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [118]:
vector = np.array([1, 2, 3, 4, 5])

expanded_vector = np.zeros(len(vector) * 4 - 1)

expanded_vector[::4] = vector

print(expanded_vector)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0.]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [130]:
import numpy as np
from numpy.lib.stride_tricks import as_strided

# Given array
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

# Create a view of the array with a new shape
b = as_strided(a, shape=(11, 4), strides=(a.strides[0], a.strides[0]))

# Print the resulting array
print(b)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [ ]:
b = as_strided(a, shape=(4, 4), strides=(a.strides[0], a.strides[0]))

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [140]:
import numpy as np

# Create a random array with some duplicate values
random_array = np.random.randint(low=0, high=5, size=10)
random_array[3] = random_array[2]
random_array[5] = random_array[0]
random_array[8] = random_array[4]
random_array

# Find the unique values in the array
unique_values = np.unique(random_array)

# Initialize an empty dictionary to store the counts
value_counts = {}

# Loop through the unique values and count their occurrences
for value in unique_values:
    value_counts[value] = np.count_nonzero(random_array == value)

# Print the value counts
print(value_counts)
random_array

{0: 1, 1: 2, 2: 2, 4: 5}


array([4, 0, 1, 1, 4, 4, 4, 2, 4, 2])

In [133]:
data = [5,2,3,8,9,7,4,2,3]
arrx = np.array(data)
np.bincount(arrx)

array([0, 0, 2, 2, 1, 1, 0, 1, 1, 1])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

#Ixtiyoriy ikkita alohida massiv yarating va birinchi massiv elementlari ikkinchi massivda mavjud ekanligini tekshiring

In [141]:
arr1 = np.array([1,2,5,3,7,8])
arr2 = np.array([0,1,3,5])
np.in1d(arr1, arr2)

array([ True, False,  True,  True, False, False])

In [143]:
data = np.array('Rahmat')
print(data)

Rahmat
