<a href="https://colab.research.google.com/github/sunnatillo91/ai-datascience/blob/main/numpy_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum
Ma'lumotlar tahlili. NumPy kutubxonasi.


*Chiziqli* algebra

In [2]:
import numpy as np

In [12]:
x = np.array([[1,2,3], [4,5,6]])

In [6]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
y = np.array([[5,5,5],[4,4,4]])

In [8]:
y

array([[5, 5, 5],
       [4, 4, 4]])

In [9]:
x+y

array([[ 6,  7,  8],
       [ 8,  9, 10]])

In [10]:
x-y

array([[-4, -3, -2],
       [ 0,  1,  2]])

In [11]:
x*4

array([[ 4,  8, 12],
       [16, 20, 24]])

In [13]:
x = np.array([[1,2,3], [4,5,6]])

In [14]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
y = np.array([[1,2], [5,6], [-1,7]])
y

array([[ 1,  2],
       [ 5,  6],
       [-1,  7]])

# Matritsalarni o'zaro ko'paytirish

In [16]:
x.dot(y)  # x*y

array([[ 8, 35],
       [23, 80]])

In [17]:
np.dot(x,y)  # x*y

array([[ 8, 35],
       [23, 80]])

In [18]:
y.dot(x)  # y*x

array([[ 9, 12, 15],
       [29, 40, 51],
       [27, 33, 39]])

In [19]:
np.dot(y, x)  # y*x

array([[ 9, 12, 15],
       [29, 40, 51],
       [27, 33, 39]])

In [20]:
# Linear Algebra
from numpy .linalg import inv