<a href="https://colab.research.google.com/github/sunnatillo91/ai-datascience/blob/main/numpy_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science va Sun'iy Intellekt Praktikum
Ma'lumotlar tahlili. NumPy kutubxonasi.


Fayllar bilan ishlash

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Faylni saqlash

In [4]:
np.save('data', arr)

# Faylni yuklab undan foydalanish

In [7]:
arr2 = np.load('data.npy')

In [8]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr1 = np.arange(20)

In [17]:
np.savez('arrays', a = arr, b = arr1)

In [18]:
arrays = np.load('arrays.npz')

In [19]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
# savesz_compressed
np.savez_compressed('array_comp.npz', a=arr, b=arr1)